import { defineArrayMember, defineField, defineType } from "sanity";

export const landingPage = defineType({
  name: "landingPage",
  title: "Landing Page",
  type: "document",
  description:
    "Homepage content for one locale. This document is edited through fixed Studio entries for SK and EN.",
  groups: [
    { name: "general", title: "General", default: true },
    { name: "seo", title: "SEO" },
    { name: "navigation", title: "Navigation" },
    { name: "hero", title: "Hero" },
    { name: "gallery", title: "Photos & Gallery" },
    { name: "overview", title: "Problem / Intro" },
    { name: "features", title: "Benefits & Equipment" },
    { name: "process", title: "How It Works" },
    { name: "cms", title: "Pricing" },
    { name: "booking", title: "Booking" },
    { name: "locations", title: "Locations" },
    { name: "faq", title: "FAQ" },
    { name: "finalCta", title: "Reservation CTA" },
    { name: "footer", title: "Brand & Contact" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Internal title",
      type: "string",
      group: "general",
      description: "Only visible inside Studio, not on the public website.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "locale",
      title: "Locale",
      type: "string",
      group: "general",
      options: {
        layout: "radio",
        list: [
          { title: "Slovak", value: "sk" },
          { title: "English", value: "en" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seoSettings",
      group: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "navigation",
      title: "Header navigation",
      type: "array",
      group: "navigation",
      of: [defineArrayMember({ type: "navItem" })],
      validation: (rule) => rule.min(1).max(6),
    }),
    defineField({
      name: "hero",
      title: "Hero section",
      type: "heroSection",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Photo gallery and visual cards",
      type: "gallerySection",
      group: "gallery",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "overviewSection",
      title: "Overview section lead",
      type: "sectionIntro",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "highlights",
      title: "Problem / intro cards",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "highlightItem" })],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "proofStrip",
      title: "Trust / quick info strip",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "features",
      title: "Benefits and equipment cards",
      type: "array",
      group: "features",
      of: [defineArrayMember({ type: "featureItem" })],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "featuresSection",
      title: "Benefits section lead",
      type: "sectionIntro",
      group: "features",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "processSection",
      title: "Process section lead",
      type: "sectionIntro",
      group: "process",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "process",
      title: "How-it-works steps",
      type: "array",
      group: "process",
      of: [defineArrayMember({ type: "processStep" })],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "cms",
      title: "Pricing section",
      type: "cmsSection",
      group: "cms",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "booking",
      title: "Booking section",
      type: "bookingSection",
      group: "booking",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "locations",
      title: "Locations section",
      type: "locationsSection",
      group: "locations",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "faq",
      title: "FAQ entries",
      type: "array",
      group: "faq",
      of: [defineArrayMember({ type: "faqItem" })],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "faqSection",
      title: "FAQ section lead",
      type: "sectionIntro",
      group: "faq",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "finalCta",
      title: "Final CTA",
      type: "finalCtaSection",
      group: "finalCta",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "footer",
      title: "Footer",
      type: "footerContent",
      group: "footer",
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: {
      title: "title",
      locale: "locale",
    },
    prepare({ title, locale }) {
      return {
        title: title || "Untitled landing page",
        subtitle: locale ? locale.toUpperCase() : "Locale not set",
      };
    },
  },
});
